### ISSUE TITLE
about dataset used for training

### ISSUE THREAD

**Issue by sanjaysswami** [Abdul-Mukit/dope_with_hand_tracking#2]
@Abdul-Mukit Did you used real dataset or synthetic datsatet? And in both cases how did you create the mesh/3D model for handglows?

**Comment by Abdul-Mukit** [comment]
The target object for DOPE was the cautery pen or the other ycb objects.
The target object for yolo2 was hand. You can check out my repository on robust hand tracking if you want to implement the hand tracking.

I used a synthetic dataset for training DOPE to track the cautery pen. I didn't train DOPE for the other YCB objects. For them, I used the already available weights.
I used real dataset for training yolo to track hand. You can find details about that in my other repository.

If you are interested in creating a 3D model, I would suggest start with Blender. I use that for this research.

**Comment by sanjaysswami** [comment]
@Abdul-Mukit Cool. Nice work. Can you please tell me how did you create the real data-set for training?

**Comment by Abdul-Mukit** [comment]
@sanjaysswami Thanks. Please go through the readme of this repo. That should answer your question.
