### ISSUE TITLE
how can orientation of the 3d model while scenecapturing be done? #NDDS #fbxmodel #dataset

### ISSUE THREAD

**Issue by avinashsen707** [Abdul-Mukit/dope_with_hand_tracking#3]
can you share your approch that done in youtube video that the 3d model you created also randomly rotated in 3d inside the workspace.
i loaded my 3d model inside UE4 , but failede to give random 360 movement for the model that is done in blender(fbx format)\
 Thanking you for the youtube channel; helped alot while i got stucked in NDDS for few weeks!

**Comment by Abdul-Mukit** [comment]
Hi. I didn't move the object. I kept the object stationary and rotated/moved the camera around it in a specified manner. There is a blueprint/object/component called something like "orbital movement". If you add that to your camera you can control how that camera moves. You can add that component to any object in fact. Please go through the issues of "DOPE" and "NDDS" GitHub repos. There I asked these questions to the authors and they provided good answers. They are very responsive, you can ask them if you don't understand the documentation too.

**Comment by avinashsen707** [comment]
thankyou @Abdul-Mukit  ; let me look into the respective steps and convey you back ASAP😊
